"""
sigma_generator.py
Reads detection gaps from the validator and auto-generates
valid Sigma rules for each undetected technique.

Output: sigma_rules/<TECHNIQUE_ID>.yml
"""

import yaml
import logging
from datetime import datetime, timezone
from pathlib import Path
from rich.console import Console
from rich.table   import Table

console = Console()
logger  = logging.getLogger(__name__)

# ── Sigma rule templates keyed by tactic ──────────────────────────────
# Each template defines the detection logic scaffold for that tactic.
# IOCs extracted from telemetry are injected into the condition block.

TACTIC_TEMPLATES = {
    "discovery": {
        "logsource": {
            "category": "process_creation",
            "product":  "macos",
        },
        "condition_field": "CommandLine|contains|all",
    },
    "execution": {
        "logsource": {
            "category": "process_creation",
            "product":  "macos",
        },
        "condition_field": "CommandLine|contains",
    },
    "persistence": {
        "logsource": {
            "category": "file_event",
            "product":  "macos",
        },
        "condition_field": "TargetFilename|contains",
    },
    "lateral_movement": {
        "logsource": {
            "category": "network_connection",
            "product":  "macos",
        },
        "condition_field": "DestinationPort|contains",
    },
}

DEFAULT_TEMPLATE = {
    "logsource": {
        "category": "process_creation",
        "product":  "macos",
    },
    "condition_field": "CommandLine|contains",
}

# ── IOC → Sigma condition mapping ─────────────────────────────────────
# Maps IOC types from telemetry to Sigma detection fields.

IOC_FIELD_MAP = {
    "process":             "Image|endswith",
    "pattern":             "CommandLine|contains",
    "path":                "CommandLine|contains",
    "artifact":            "TargetFilename|contains",
    "security_tool_found": "CommandLine|contains",
}


class SigmaRule:
    """Represents a single generated Sigma rule."""

    def __init__(
        self,
        technique_id: str,
        name:         str,
        tactic:       str,
        iocs:         list,
        description:  str = "",
    ):
        self.technique_id = technique_id
        self.name         = name
        self.tactic       = tactic
        self.iocs         = iocs
        self.description  = description
        self.rule_id      = f"PW-{technique_id.replace('.', '-')}"
        self.generated_at = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> dict:
        """Build the full Sigma rule as a Python dict (serialised to YAML)."""
        template = TACTIC_TEMPLATES.get(self.tactic.lower(), DEFAULT_TEMPLATE)

        # ── Build detection block from IOCs ───────────────────────
        detection_values: dict[str, list] = {}

        for ioc in self.iocs:
            ioc_type  = ioc.get("type", "pattern")
            ioc_value = ioc.get("value", "")
            if not ioc_value:
                continue

            field = IOC_FIELD_MAP.get(ioc_type, "CommandLine|contains")
            detection_values.setdefault(field, [])

            # deduplicate
            if ioc_value not in detection_values[field]:
                detection_values[field].append(ioc_value)

        # ── Fallback if no IOCs ────────────────────────────────────
        if not detection_values:
            detection_values["CommandLine|contains"] = [
                self.technique_id.lower().replace(".", "_")
            ]

        # ── Sigma condition logic ──────────────────────────────────
        # Single field → simple 'selection'
        # Multiple fields → named selections ANDed together
        if len(detection_values) == 1:
            field, values = next(iter(detection_values.items()))
            detection_block = {
                "selection": {field: values},
            }
            condition = "selection"
        else:
            detection_block = {}
            sel_names       = []
            for i, (field, values) in enumerate(detection_values.items()):
                sel_name = f"sel_{i+1}"
                detection_block[sel_name] = {field: values}
                sel_names.append(sel_name)
            condition = " and ".join(sel_names)

        detection_block["condition"] = condition

        # ── Assemble full rule ─────────────────────────────────────
        rule = {
            "title":       f"PhantomWatch: {self.name}",
            "id":          self.rule_id,
            "status":      "experimental",
            "description": (
                self.description or
                f"Auto-generated by PhantomWatch for {self.technique_id}. "
                f"Detects {self.name} activity on macOS. "
                f"Tactic: {self.tactic}. Review and tune before production use."
            ),
            "references": [
                f"https://attack.mitre.org/techniques/{self.technique_id.replace('.', '/')}/"
            ],
            "author":    "PhantomWatch (auto-generated)",
            "date":      datetime.now(timezone.utc).strftime("%Y/%m/%d"),
            "tags": [
                f"attack.{self.tactic}",
                f"attack.{self.technique_id.lower().replace('.', '_')}",
            ],
            "logsource":  template["logsource"],
            "detection":  detection_block,
            "falsepositives": [
                "Legitimate administrative activity",
                "Security tooling and scanners",
                "Developer environments",
            ],
            "level": "medium",
        }

        return rule

    def to_yaml(self) -> str:
        """Serialise the rule to Sigma-compliant YAML."""
        return yaml.dump(
            self.to_dict(),
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )


class SigmaGenerator:
    """
    Reads gap results from DetectionValidator and writes Sigma rules.

    Usage:
        generator = SigmaGenerator()
        rules     = generator.generate(gaps)
        generator.save(rules)
        generator.print_summary(rules)
    """

    def __init__(self, output_dir: str = "sigma_rules"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    # ------------------------------------------------------------------ #
    #  Generation                                                          #
    # ------------------------------------------------------------------ #

    def generate(self, gaps: list) -> list[SigmaRule]:
        """
        Generate one Sigma rule per gap result.
        Pulls IOCs from telemetry if present, falls back to technique metadata.
        """
        rules   = []
        seen    = set()

        for result in gaps:
            tid = result.technique_id
            if tid in seen:
                continue
            seen.add(tid)

            # pull IOCs from real telemetry if available
            telemetry = getattr(result, "telemetry", {})
            iocs      = telemetry.get("iocs", []) if telemetry else []

            # fallback IOC from technique name keywords
            if not iocs:
                iocs = self._infer_iocs(result)

            tactic = result.tactics[0] if result.tactics else "execution"

            rule = SigmaRule(
                technique_id = tid,
                name         = result.name,
                tactic       = tactic,
                iocs         = iocs,
                description  = (
                    f"Detects {result.name} ({tid}). "
                    f"Auto-generated from PhantomWatch simulation gap. "
                    f"Platforms: {', '.join(getattr(result, 'platforms', []))}."
                ),
            )
            rules.append(rule)
            logger.info(f"Generated Sigma rule for {tid}: {rule.rule_id}")

        console.print(
            f"[bold green]✓ Generated {len(rules)} Sigma rules "
            f"from {len(gaps)} gaps[/bold green]"
        )
        return rules

    def _infer_iocs(self, result) -> list:
        """
        Infer basic IOCs from technique name when no telemetry is available.
        Used as fallback for stub-simulated techniques.
        """
        name_words = result.name.lower().split()
        return [
            {"type": "pattern", "value": w}
            for w in name_words
            if len(w) > 4 and w not in {
                "and", "the", "via", "from", "with", "using"
            }
        ]

    # ------------------------------------------------------------------ #
    #  Output                                                              #
    # ------------------------------------------------------------------ #

    def save(self, rules: list[SigmaRule]) -> list[str]:
        """Write each rule to sigma_rules/<TECHNIQUE_ID>.yml"""
        saved = []
        for rule in rules:
            filename = f"{rule.technique_id.replace('.', '_')}.yml"
            path     = self.output_dir / filename
            path.write_text(rule.to_yaml())
            saved.append(str(path))
            logger.info(f"Saved: {path}")

        console.print(
            f"[bold green]✓ Saved {len(saved)} rules → "
            f"{self.output_dir}/[/bold green]"
        )
        return saved

    def save_bundle(self, rules: list[SigmaRule]) -> str:
        """Write all rules into a single phantomwatch_bundle.yml file."""
        bundle_path = self.output_dir / "phantomwatch_bundle.yml"
        with open(bundle_path, "w") as f:
            f.write("# PhantomWatch Sigma Rule Bundle\n")
            f.write(f"# Generated: {datetime.now(timezone.utc).isoformat()}\n")
            f.write(f"# Rules: {len(rules)}\n")
            f.write("# " + "─" * 60 + "\n\n")
            for rule in rules:
                f.write(rule.to_yaml())
                f.write("\n---\n\n")

        console.print(
            f"[bold green]✓ Bundle saved → {bundle_path}[/bold green]"
        )
        return str(bundle_path)

    def print_summary(self, rules: list[SigmaRule]):
        """Rich table of all generated rules."""
        table = Table(title="PhantomWatch — Generated Sigma Rules", style="cyan")
        table.add_column("Rule ID",    style="bold yellow", no_wrap=True)
        table.add_column("Technique",  style="dim",         no_wrap=True)
        table.add_column("Name",       style="white")
        table.add_column("Tactic",     style="dim")
        table.add_column("IOC Count",  style="green", justify="right")
        table.add_column("Level",      style="magenta")

        for rule in rules:
            d = rule.to_dict()
            table.add_row(
                rule.rule_id,
                rule.technique_id,
                rule.name[:45],
                rule.tactic.replace("-", " ").title(),
                str(len(rule.iocs)),
                d.get("level", "medium"),
            )

        console.print(table)
