"""
sigma_tuner.py
Post-processes generated Sigma rules — adds FP filters,
severity scoring, and tuning metadata.
"""

import yaml
import logging
from pathlib  import Path
from datetime import datetime, timezone
from rich.console import Console
from rich.table   import Table

console = Console()
logger  = logging.getLogger(__name__)

# ── Severity scoring rules ─────────────────────────────────────────────
# Maps tactic + IOC patterns to severity levels
SEVERITY_MAP = {
    "credential_access": "high",
    "credential-access": "high",
    "persistence":       "high",
    "execution":         "medium",
    "discovery":         "low",
    "lateral_movement":  "high",
    "lateral-movement":  "high",
    "exfiltration":      "critical",
    "impact":            "critical",
}

# ── False positive filter templates per tactic ─────────────────────────
FP_FILTERS = {
    "discovery": {
        "filter_admin": {
            "User|contains": ["root", "admin", "_spotlight", "_mdnsresponder"]
        }
    },
    "execution": {
        "filter_dev": {
            "CommandLine|contains": [
                "venv", "pytest", "pip install",
                "brew", "xcode", "Xcode",
            ]
        }
    },
    "persistence": {
        "filter_legit": {
            "TargetFilename|contains": [
                "com.apple.", "com.google.", "com.microsoft.",
                "homebrew", "Homebrew",
            ]
        }
    },
    "credential-access": {
        "filter_system": {
            "User|contains": ["root", "_securityagent", "_keychaind"]
        }
    },
    "credential_access": {
        "filter_system": {
            "User|contains": ["root", "_securityagent", "_keychaind"]
        }
    },
}

# ── MITRE tactic → ATT&CK tag ──────────────────────────────────────────
TACTIC_TAG_MAP = {
    "discovery":         "attack.discovery",
    "execution":         "attack.execution",
    "persistence":       "attack.persistence",
    "credential_access": "attack.credential_access",
    "credential-access": "attack.credential_access",
    "lateral_movement":  "attack.lateral_movement",
    "lateral-movement":  "attack.lateral_movement",
    "exfiltration":      "attack.exfiltration",
    "impact":            "attack.impact",
    "collection":        "attack.collection",
    "defense_evasion":   "attack.defense_evasion",
}


class SigmaTuner:
    """
    Post-processes Sigma rules generated by SigmaGenerator.
    Adds FP filters, severity scoring, tuning notes, and
    MITRE tags. Rewrites rules in-place or to a new directory.

    Usage:
        tuner  = SigmaTuner()
        tuned  = tuner.tune(rules)
        tuner.save(tuned)
        tuner.print_summary(tuned)
    """

    def __init__(self, output_dir: str = "sigma_rules/tuned"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    #  Tuning                                                              #
    # ------------------------------------------------------------------ #

    def tune(self, rules: list) -> list[dict]:
        """
        Apply FP filters + severity scoring to a list of SigmaRule objects.
        Returns list of tuned rule dicts ready for YAML serialisation.
        """
        tuned = []
        for rule in rules:
            try:
                d = self._tune_one(rule)
                tuned.append(d)
            except Exception as e:
                logger.warning(f"Failed to tune {rule.rule_id}: {e}")

        console.print(
            f"[bold green]✓ Tuned {len(tuned)} Sigma rules — "
            f"FP filters + severity applied[/bold green]"
        )
        return tuned

    def _tune_one(self, rule) -> dict:
        """Apply all tuning passes to a single SigmaRule."""
        d = rule.to_dict()

        # ── 1. Severity scoring ────────────────────────────────────
        severity = SEVERITY_MAP.get(rule.tactic.lower(), "medium")
        d["level"] = severity

        # ── 2. FP filter injection ─────────────────────────────────
        fp_template = FP_FILTERS.get(rule.tactic.lower(), {})
        if fp_template:
            for filter_name, filter_def in fp_template.items():
                d["detection"][filter_name] = filter_def

            # Update condition to exclude FP filter
            existing = d["detection"].get("condition", "selection")
            filter_names = " and not ".join(fp_template.keys())
            d["detection"]["condition"] = f"({existing}) and not ({filter_names})"

        # ── 3. Enrich tags ─────────────────────────────────────────
        tactic_tag = TACTIC_TAG_MAP.get(rule.tactic.lower(), f"attack.{rule.tactic}")
        tech_tag   = f"attack.{rule.technique_id.lower().replace('.', '_')}"
        d["tags"]  = list(set(d.get("tags", []) + [tactic_tag, tech_tag]))

        # ── 4. Tuning metadata ─────────────────────────────────────
        d["tuned"]          = True
        d["tuned_at"]       = datetime.now(timezone.utc).strftime("%Y/%m/%d")
        d["tuning_version"] = "1.0"
        d["falsepositives"] = [
            "Legitimate administrative activity",
            "Security tooling (CrowdStrike, SentinelOne, osquery)",
            "Developer environments (venv, brew, Xcode)",
            "System processes (com.apple.*)",
        ]

        return d

    # ------------------------------------------------------------------ #
    #  Output                                                              #
    # ------------------------------------------------------------------ #

    def save(self, tuned_rules: list[dict]) -> list[str]:
        """Write tuned rules to sigma_rules/tuned/"""
        saved = []
        for rule in tuned_rules:
            tid      = rule.get("id", "UNKNOWN").replace("PW-", "")
            filename = f"{tid}.yml"
            path     = self.output_dir / filename
            path.write_text(
                yaml.dump(rule, default_flow_style=False,
                          sort_keys=False, allow_unicode=True)
            )
            saved.append(str(path))

        console.print(
            f"[bold green]✓ Saved {len(saved)} tuned rules → "
            f"{self.output_dir}/[/bold green]"
        )
        return saved

    def save_tuned_bundle(self, tuned_rules: list[dict]) -> str:
        """Write all tuned rules to a single bundle file."""
        bundle_path = self.output_dir / "phantomwatch_tuned_bundle.yml"
        with open(bundle_path, "w") as f:
            f.write("# PhantomWatch Tuned Sigma Bundle\n")
            f.write(f"# Generated: {datetime.now(timezone.utc).isoformat()}\n")
            f.write(f"# Rules: {len(tuned_rules)}\n")
            f.write(f"# Tuning: FP filters + severity scoring applied\n")
            f.write("# " + "─" * 60 + "\n\n")
            for rule in tuned_rules:
                f.write(yaml.dump(rule, default_flow_style=False,
                                  sort_keys=False, allow_unicode=True))
                f.write("\n---\n\n")

        console.print(
            f"[bold green]✓ Tuned bundle → {bundle_path}[/bold green]"
        )
        return str(bundle_path)

    def print_summary(self, tuned_rules: list[dict]):
        """Rich table of tuned rules with severity breakdown."""
        table = Table(title="PhantomWatch — Tuned Sigma Rules", style="cyan")
        table.add_column("Rule ID",   style="bold yellow", no_wrap=True)
        table.add_column("Technique", style="dim",         no_wrap=True)
        table.add_column("Tactic",    style="white")
        table.add_column("Severity",  style="magenta")
        table.add_column("FP Filter", style="green")
        table.add_column("Tags",      style="dim")

        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}

        for rule in tuned_rules[:40]:
            severity = rule.get("level", "medium")
            counts[severity] = counts.get(severity, 0) + 1
            has_fp   = "✓" if rule.get("tuned") else "—"
            tags     = ", ".join(rule.get("tags", []))[:40]
            sev_color = {
                "critical": "red",
                "high":     "yellow",
                "medium":   "cyan",
                "low":      "dim",
            }.get(severity, "white")

            table.add_row(
                rule.get("id", "—"),
                rule.get("id", "—").replace("PW-", ""),
                rule.get("tags", [""])[0].replace("attack.", ""),
                f"[{sev_color}]{severity}[/{sev_color}]",
                has_fp,
                tags,
            )

        console.print(table)
        console.print(
            f"\n[bold]Severity breakdown:[/bold] "
            f"[red]Critical: {counts.get('critical',0)}[/red] | "
            f"[yellow]High: {counts.get('high',0)}[/yellow] | "
            f"[cyan]Medium: {counts.get('medium',0)}[/cyan] | "
            f"[dim]Low: {counts.get('low',0)}[/dim]"
        )
